### ISSUE TITLE
[Feature Request] Switch to native emoji keyboard

### ISSUE THREAD

**Issue by yasinarik** [jpnurmi/keyboard_info#2]
Hi! Thanks for making this package.

I wonder if there is a chance that you can add the functionality that lets switch between the **native** emoji keyboard and native text keyboard of the device?

**Comment by jpnurmi** [comment]
Hi, as the `keyboard_info` name suggests, the scope of the package is to query _info_ about the system keyboard. I'm afraid manipulating the keyboard is out of scope for this package.
